import BookAdditionForm from 'c/bookAdditionForm';

describe('c-book-addition-form', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-book-addition-form', {
            is: BookAdditionForm
        });
        document.body.appendChild(element);
        expect(1).toBe(1);
    });
});
